swagger: "2.0"
info:
  title: Money tarnsfer API
  description: API.
  version: 1.0.0
host: localhost:8080
schemes:
  - https
paths:
  /account/clientName:
    get:
      summary: Returns an account of client.
      produces:
        - application/json
      responses:
        200:
          description: OK
        400:
          description: Not fount account for the client
  /account:
    post:
      summary: Create an account.
      description: .
      produces:
        - application/json
      responses:
        200:
          description: OK
        400:
          description: Account already exist
  /transaction:
    get:
      summary: Returns all transactions.
      produces:
        - application/json
      responses:
        200:
          description: OK
    post:
      summary: Perform transaction
      produces:
        - application/json
      responses:
        200:
          description: OK
        400:
          description: Error appeared
